//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.View.Modules
{
    public partial class Adduser
    {
    }
}
