//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.View.Modules
{
    public partial class EmployeeLeaveList
    {
        /// <summary>
        /// UpdatePanel1 control.
        /// </summary>
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        /// <summary>
        /// gridview control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gridview;
    }
}

