//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.View.Modules
{
    public partial class EmployeeLeaveView
    {
        protected global::System.Web.UI.WebControls.TextBox txtStartDate;
        protected global::System.Web.UI.WebControls.TextBox txtEndDate;
        protected global::System.Web.UI.WebControls.TextBox txtApprovalStatus;
        protected global::System.Web.UI.WebControls.TextBox txtLookupId;
        protected global::System.Web.UI.WebControls.TextBox txtLeaveTypeId;
        protected global::System.Web.UI.WebControls.TextBox txtApprovedFromDate;
        protected global::System.Web.UI.WebControls.TextBox txtApprovedToDate;
        protected global::System.Web.UI.WebControls.TextBox txtDescription;
        protected global::System.Web.UI.WebControls.TextBox txtRejectionRemark;
        protected global::System.Web.UI.WebControls.Button btnBack;
    }
}
